title: Regina Chitralla's Portfolio
description: Portfolio of Regina Chitralla showcasing programming projects and professional experience.
baseurl: ""
url: "https://rchitralla.github.io"
theme: jekyll-theme-modernist
include:
  - projects
collections:
  projects:
    output: true
