title: Regina Chitralla
description: Data Analytics & AI Implementation consultant. Secure analytics, data engineering and AI governance.
baseurl: ""
url: "https://rchitralla.github.io"
lang: en
author: Regina Chitralla

plugins:
  - jekyll-seo-tag
