title: Regina Chitralla
description: Technical Project Manager and Data Analytics Consultant. Portfolio, experience, and technical articles.
baseurl: ""
url: "https://rchitralla.github.io"
lang: en
author: Regina Chitralla

plugins:
  - jekyll-seo-tag
